### ISSUE TITLE
Import Subjects dialog does not open on Windows 10 / 0.5.6 / database 0013

### ISSUE THREAD

**Issue by gregorschulte-uni** [bendalab/animal_keeping#81]

**Comment by jgrewe** [comment]
I could not reproduce this bug on a freshly installed win 10 with JRE version8 update 161. Will try it on a different system...

**Comment by jgrewe** [comment]
on a second windows 10 I could kind-of reproduce the effect. Since the connection to the database was slow(er) from home, initializing and populating the drop-down boxes took much longer and the dialog opened with a certain delay.

Will try to improve this by using lazy loading where possible in the next time.
